version: '2'
services:
  web:
    build: .
    image: gcr.io/percy_dev/web:local
    ports:
      - "8080:8080"
    environment:
     - PERCY_TOKEN=${PERCY_TOKEN}
     - PERCY_PROJECT=${PERCY_PROJECT}
     - PERCY_COMMIT=${PERCY_COMMIT}
